#page title
page_title                                : CrakX App                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                             # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : "play.google.com/store/apps/details?id=io.iitb.firebase_test"                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CrakX                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Transforming your Preparation                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Navigate through our vast collection of resume resources, interview questions, personal experiences, and tips from various successful candidates and cover letters for portraying your personality in the best way. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : CrakX                                
your_link                                 : https://crakx.github.io                     
your_city                                 : Lockdown                                
email_address                             : crakxapp@gmail.com
facebook_username                         : Crakxapp
instagram_username                        : crakxapp
twitter_username                          : 
github_username                           : crakx
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Resume Repository
    description                           : Get Inspirations to make your resume according to the company which you are planning to apply, whether it be core or non core. Voila! 
    fontawesome_icon_name                 : folder
    
  - title                                 : Stories
    description                           : Want to know how your seniors get their prepration done for their placements or internships? Check our stories section which includes a good collection of such stories! 
    fontawesome_icon_name                 : child

  - title                                 : Cover letters
    description                           : A vast collection of Statement of purpose or cover letters which you might need for your company application, MS/PhD or Apping. 
    fontawesome_icon_name                 : university

  - title                                 : Interview Questions
    description                           : A complete resource of company wise interview questions asked in last 5 years.
    fontawesome_icon_name                 : question-circle

  - title                                 : Prepration Arena
    description                           : Collection of Cheat sheets related to Algorithms, Data structure, Apptitude and languages which could help you in end moments just before your test or interview 
    fontawesome_icon_name                 : code
  
  - title                                 : Fundaes
    description                           : Get awesome fundaes which you need to master interview skills, get through those placement/ internship tests and how to make your timetable for whole hactic placement process.
    fontawesome_icon_name                 : star

  - title                                 : Favourite
    description                           : Mark important resume or any resource as favourite so that you can read whenever you want
    fontawesome_icon_name                 : bookmark

  - title                                 : App Support
    description                           : Easy app support to report any bugs or issues related to our app
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.15
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#1d63ea"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
